name: Push librs changes to BlueOS
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: blueos-push-${{ github.repository }}
  cancel-in-progress: false
jobs:
  push:
    if: ${{ vars.JOSH_SYNC_ENABLED == 'true' }}
    uses: vivoblueos/josh-sync/.github/workflows/blueos-push.yml@0e9e37f4fa9c8f260db26fcae8550a941e9cee5d
    with:
      github-app-client-id: ${{ vars.JOSH_SYNC_APP_CLIENT_ID }}
      pr-author: "blueos-josh-sync[bot]"
      josh-sync-repository: vivoblueos/josh-sync
      josh-sync-revision: 0e9e37f4fa9c8f260db26fcae8550a941e9cee5d
    secrets:
      github-app-secret: ${{ secrets.JOSH_SYNC_APP_PRIVATE_KEY }}
      approval-user-token: ${{ secrets.JOSH_SYNC_APPROVAL_USER_TOKEN }}
